### ISSUE TITLE
Missing printer-sovol-sv08-2024.cfg

### ISSUE THREAD

**Issue by mikekasprzak** [Sovol3d/SV08#1]
Checking in `home/sovol/klipper/config/`, I couldn't find a configuration for the SV08.

**Comment by Sovol3d** [comment]
In this directory home/sovol/printer_data/config/

**Comment by mikekasprzak** [comment]
Got it. I suppose I wasn't expecting the dimensions to be 355x367x347. Thanks for pointing me in the right direction.
