### ISSUE TITLE
I cant connect to wifi.cfg

### ISSUE THREAD

**Issue by ViktorRindom** [Sovol3d/SV08#17]
I have checked the data in the wifi cfg but it wont connect.

I update the printer to firmware version 2.3.3 using another usb but the issue is still there. 

I have also created the wifi.cfg on a third usb stick and that did also not work. the ip stays on the default ip (127... not connected)

wifi.cfg:
```
ssid=Zyxel_1F1F
password=PASSWORDHERE
```
note: PASSWORDHERE is replaced with the correct passsword.

![image](https://github.com/user-attachments/assets/f49c20e6-fe65-418a-99ff-5b5e0d8ea939)

I am using the 2.4 gh

I have had the file on the usb stick i use to print the hole time i have used the printer and the info is correct but it does not connect. I run a angryipscanner check every now and then. But the printer never shows up and show ip is always the default ip.

**Comment by FCosta1** [comment]
watch after 5:23minutes
https://www.youtube.com/watch?v=OgX14lbYAJw&t=359s
you have the solution there

**Comment by ViktorRindom** [comment]
Thank you very much. i now have a wifi ip i can use. I will betesting it today.

**Comment by ViktorRindom** [comment]
It worked thanks
