### ISSUE TITLE
Toolhead board bl-touch connector

### ISSUE THREAD

**Issue by ArnoldWildt** [Sovol3d/SV08#2]
In this [Motherboard/Extra_PIN_definition.pdf](../blob/main/Motherboard/Extra_PIN_definition.pdf) the bl-touch connector is supplied with 24V, but the bl-touch needs 5V.

Is the connector wrong labeled, or is the board really supplying 24V to the connector?

**Comment by ArnoldWildt** [comment]
According to the documentation for the [Proximity switch](https://github.com/Sovol3d/SV08/blob/main/PDF/20%E7%94%B5%E5%99%A8%E5%85%83%E5%99%A8%E4%BB%B6Electronic%20component/JXHSV08-06040-f%EF%BC%88Proximity%20switch%EF%BC%89.pdf%20_%20Sider%20PDF%20translate_.pdf)
The proximity switch is powered by 24V, so the label with 24V is right. :(
The proximity switch is plugged into the bl-touch connector.

**Comment by Sovol3d** [comment]
Hi,
Thank you for your email and suggestions. We recommend that you join our group chat directly to explore with more friends. Thank you.
https://www.facebook.com/groups/sovol3d <https://www.facebook.com/groups/sovol3d >
Best regards,
Sovol After Sales Department
website: sovol3d.com
Follow us to get exclusive 3D printing information
Sovol Official User Group: https://www.facebook.com/groups/sovol3d <https://www.facebook.com/sovol3d/ >
Facebook Page:https://www.facebook.com/sovol3d <https://twitter.com/Sovol3d >
Youtube: https://www.youtube.com/channel/UCsKntuwh7dhAGep8R6kasog <https://www.youtube.com/channel/UCsKntuwh7dhAGep8R6kasog >
------------------------------------------------------------------
From:Arnold Wildt ***@***.***>
Send Time:2024年4月27日(星期六) 03:01
To:Sovol3d/SV08 ***@***.***>
Cc:Subscribed ***@***.***>
Subject:Re: [Sovol3d/SV08] Toolhead board bl-touch connector (Issue #2)
According to the documentation for the Proximity switch <https://github.com/Sovol3d/SV08/blob/main/PDF/20%E7%94%B5%E5%99%A8%E5%85%83%E5%99%A8%E4%BB%B6Electronic%20component/JXHSV08-06040-f%EF%BC%88Proximity%20switch%EF%BC%89.pdf%20_%20Sider%20PDF%20translate_.pdf >
 The proximity switch is powered by 24V, so the label with 24V is right. :(
 The proximity switch is plugged into the bl-touch connector.

**Comment by SphaeroX** [comment]
u could use the 5V from Uart :)
