### ISSUE TITLE
OrcaSlicer Profiles

### ISSUE THREAD

**Issue by mon5termatt** [Sovol3d/SV08#3]
It would be super nice to have the profiles on the github here so people without the printer can look at the settings and options.

**Comment by Sovol3d** [comment]
Hello,
Please refer to the link:
https://github.com/Sovol3d/SV08 <https://github.com/Sovol3d/SV08 >
Best regards,
Sovol After Sales Department
website: sovol3d.com
Follow us to get exclusive 3D printing information
Sovol Official User Group: https://www.facebook.com/groups/sovol3d <https://www.facebook.com/sovol3d/ >
Facebook Page:https://www.facebook.com/sovol3d <https://twitter.com/Sovol3d >
Youtube: https://www.youtube.com/channel/UCsKntuwh7dhAGep8R6kasog <https://www.youtube.com/channel/UCsKntuwh7dhAGep8R6kasog >
------------------------------------------------------------------
From:Matthew Clark ***@***.***>
Send Time:2024年5月10日(星期五) 05:11
***@***.***>
***@***.***>
Subject:[Sovol3d/SV08] OrcaSlicer Profiles (Issue #3)
It would be super nice to have the profiles on the github here so people without the printer can look at the settings and options.

**Comment by mon5termatt** [comment]
Where, that's just the link to this repo, the orcaslicer profiles are not on there.

**Comment by Sovol3d** [comment]
Hello, sorry for any inconvenience, please try this link: https://drive.google.com/drive/u/2/folders/1KWjLxwpO_9_Xqi_f6qu84HRxZi26a_GN <https://drive.google.com/drive/u/2/folders/1KWjLxwpO_9_Xqi_f6qu84HRxZi26a_GN > 
Thanks in advance.
Best regards,
Sovol After Sales Department
website: sovol3d.com
Follow us to get exclusive 3D printing information
Sovol Official User Group: https://www.facebook.com/groups/sovol3d <https://www.facebook.com/sovol3d/ >
Facebook Page:https://www.facebook.com/sovol3d <https://twitter.com/Sovol3d >
Youtube: https://www.youtube.com/channel/UCsKntuwh7dhAGep8R6kasog <https://www.youtube.com/channel/UCsKntuwh7dhAGep8R6kasog >
------------------------------------------------------------------
From:Matthew Clark ***@***.***>
Send Time:2024年5月10日(星期五) 13:03
***@***.***>
***@***.***>; ***@***.***>
Subject:Re: [Sovol3d/SV08] OrcaSlicer Profiles (Issue #3)
Where, that's just the link to this repo, the orcaslicer profiles are not on there.
